# Generated by Django 4.2.4 on 2023-09-04 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaysia_app', '0003_country_userprofile_group_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zikr_count',
            name='zikr_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 17, 44, 53, 986811, tzinfo=datetime.timezone.utc)),
        ),
    ]
