# Generated by Django 4.2.4 on 2023-09-04 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaysia_app', '0007_alter_zikr_count_zikr_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='group_section',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='zikr_count',
            name='zikr_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 18, 7, 50, 456180, tzinfo=datetime.timezone.utc)),
        ),
    ]
