# Generated by Django 4.2.4 on 2023-09-07 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaysia_app', '0015_alter_zikr_count_zikr_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traget_count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='zikr_count',
            name='zikr_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 9, 27, 18, 654055, tzinfo=datetime.timezone.utc)),
        ),
    ]
